[build]
  publish = "app/frontend/dist/"
  command = "cd app/frontend && npm run build"

[functions]
  directory = "netlify/functions"

# Local dev settings
[dev]
  framework = "#custom"
  command = "npm --prefix app/frontend run dev"
  targetPort = 5173
  port = 3000
  autoLaunch = false

[build.environment]
  NODE_VERSION = "22"
  VITE_API_BASE_URL = "https://8b6f43fdae68.ngrok-free.app"